#!/bin/bash

echo "🔍 Diagnosing Port Conflict"
echo "=========================="
echo ""

echo "1. Checking what's using port 80:"
echo "--------------------------------"
netstat -tlnp | grep :80 || ss -tlnp | grep :80 || echo "No process found using netstat/ss"

echo ""
echo "2. Alternative port check:"
echo "------------------------"
lsof -i :80 2>/dev/null || echo "lsof not available or no process on port 80"

echo ""
echo "3. Docker port usage:"
echo "-------------------"
docker ps --format "table {{.Names}}\t{{.Ports}}" | grep ":80"

echo ""
echo "4. Suggested solutions:"
echo "----------------------"
echo "Option 1: Use different ports for Traefik"
echo "  - Edit docker-compose.yml to use ports 8080:80 and 8443:443"
echo ""
echo "Option 2: Stop the service using port 80"
echo "  - Find the service and stop it"
echo "  - Common culprits: nginx, apache, other web servers"
echo ""
echo "Option 3: Run without Traefik (for testing)"
echo "  - Start only the core services: mongo, redis, wildduck"
echo ""

echo "5. Quick fix - Start core services only:"
echo "---------------------------------------"
echo "docker compose up -d mongo redis wildduck"
echo ""
echo "This will start the essential services without Traefik"
echo "and let us test the 60-second restart issue directly."