#!/bin/bash

echo ""
echo "========================================="
echo "✓ Setup completed successfully!"
echo "========================================="
echo ""
echo "Your WildDuck mail server is now running at:"
echo "  API:  https://$HOSTNAME/api"
echo "  Web:  https://$HOSTNAME/"
echo ""
echo "To create users, use the WildDuck API:"
echo "  curl -XPOST https://$HOSTNAME/api/users \\"
echo "    -H 'Content-type: application/json' \\"
echo "    -d '{\"username\": \"yourname\", \"password\": \"yourpassword\", \"address\": \"yourname@$MAILDOMAIN\"}'"
echo ""